name: echopype_examples
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - ipykernel
  - s3fs
  - geopandas
  - cartopy
  - scipy
  - numba # Helps ensure a recent version is installed
  - numpy<2
  - pip
  # -- holoviz --
  - jupyter_bokeh
  - datashader
  - holoviews
  - hvplot
  # -- echopype --
  # echopype main branch contains latest changes (not in the stable release)
  - pip:
    - git+https://github.com/OSOceanAcoustics/echopype.git
    - echoregions