name: echopype_examples
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - ipykernel
  - s3fs
  - geopandas
  - cartopy
  - scipy
  - echopy
  - numba # Helps ensure a recent version is installed
  # -- holoviz --
  - jupyter_bokeh
  - datashader
  - holoviews
  - hvplot
  # -- echopype --
  # latest release
  - echopype=0.9.0
  # -- echoregions --
  # main branch (contains latest changes) and conda-forge doesn't have latest pip version yet
  - pip:
    - git+https://github.com/OSOceanAcoustics/echoregions