name: echopype_examples
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - ipykernel
  - s3fs
  - geopandas
  - cartopy
  - scipy
  - numba # Helps ensure a recent version is installed
  # -- holoviz --
  - jupyter_bokeh
  - datashader
  - holoviews
  - hvplot
  # -- echopype and echoregions --
  # echopype main branch contains latest changes (not in the stable release)
  # echoregions is not on conda-forge yet
  - pip:
    - git+https://github.com/OSOceanAcoustics/echopype
    - git+https://github.com/OSOceanAcoustics/echoregions